name: pipelines_modules_docker_build
inputs:
  serviceConnection:
    required: false
    type: string
  registryUrl:
    required: false
    type: string
  serviceName:
    required: false
    type: string
  componentLibraryToken:
    required: false
    type: string
  appInsightsKey:
    required: false
    type: string
  isLatest:
    required: false
    default: false
    type: boolean
  workingDirectoryUi:
    required: false
    type: string
  sharepointCliendId:
    required: false
    type: string
  sharepointClientSecret:
    required: false
    type: string
  sharepointScope:
    required: false
    type: string
  sharepointTenantId:
    required: false
    type: string
runs:
  using: composite
  steps:
  # Unable to determine registry '${{ parameters.serviceConnection }}' type. The service connection was not found or the authentication type not supported.
  - name: Login to ACR
    uses: docker/login-action@v3.0.0
    with:
      registry: "${{ env.DOCKER_REGISTRY }}"
      username: "${{ env.DOCKER_USERNAME }}"
      password: "${{ secrets.DOCKER_PASSWORD }}"
  - name: Install PowerShell and exiftool
    run: |-
      # Install exiftool
      sudo apt-get install -y exiftool
    shell: bash
  - name: Download Images From Sharepoint
    continue-on-error: true
    run: " -workingDirectoryUi ${{ inputs.workingDirectoryUi }} -tenantId ${{ inputs.sharepointTenantId }} -clientId ${{ inputs.sharepointCliendId }} -scope ${{ inputs.sharepointScope }} -clientSecret ${{ inputs.sharepointClientSecret }}"
    shell: powershell
  - name: Pull latest Docker image for caching
    run: docker pull ${{ inputs.registryUrl }}/${{ inputs.serviceName }}:latest || true
    shell: bash
  - name: Build Docker image - Latest
    if: inputs.isLatest == true
    run: DOCKER_BUILDKIT=1 docker build -t ${{ inputs.registryUrl }}/${{ inputs.serviceName }}:${{ github.run_id }} -t ${{ inputs.registryUrl }}/${{ inputs.serviceName }}:latest --cache-from ${{ inputs.registryUrl }}/${{ inputs.serviceName }}:latest --build-arg COMPONENT_LIBRARY_TOKEN=${{ inputs.componentLibraryToken }} --build-arg APP_INSIGHTS_KEY=${{ inputs.appInsightsKey }} --build-arg APP_INSIGHTS_KEY=${{ inputs.appInsightsKey }} .
    shell: bash
  - name: Build Docker image
    if: inputs.isLatest == false
    run: DOCKER_BUILDKIT=1 docker build -t ${{ inputs.registryUrl }}/${{ inputs.serviceName }}:${{ github.run_id }} --cache-from ${{ inputs.registryUrl }}/${{ inputs.serviceName }}:latest --build-arg COMPONENT_LIBRARY_TOKEN=${{ inputs.componentLibraryToken }} --build-arg APP_INSIGHTS_KEY=${{ inputs.appInsightsKey }} .
    shell: bash
  # Unable to determine registry '${{ parameters.serviceConnection }}' type. The service connection was not found or the authentication type not supported.
  - name: Push Docker image to container registry
    run: docker push ${{ env.DOCKER_REGISTRY }}/${{ inputs.serviceName }}:${{ github.run_id }}
    shell: bash